### PR TITLE
added missing extra_media block in example base template

### PR DESCRIPTION
**Pull request by jpaniagualaconich**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jpaniagualaconich** [comment]
only now i realise example has its own base template 😅️

**Comment by jpaniagualaconich** [comment]
@claudep @moggers87 there's also this one that I overlooked.

**Review by claudep — APPROVED** [review]
Sure!

**Comment by jpaniagualaconich** [comment]
thanks! 🎉

**Pull request merged**
