### PR TITLE
Opt token are digits, not integers

### PR DESCRIPTION
**Pull request by lmignon**
Indeed, generated tokens can start with '0'. If we use an IntegerField into the form, the 0 will desapear and the value becomes invalid

## Description

Replace the IntergerField by RegexField for otp_token into AuthenticationTokenForm

## Motivation and Context

 generated tokens can start with '0'. If we use an IntegerField into the form, the 0 will desapear and the value becomes invalid

## How Has This Been Tested?
Manual test: Tested by entering valid tokens starting with '0' and invalid tokens (alpha, length< totp_digits, length> totp_digits, ...)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by moggers87** [comment]
I'm not convinced that this *is* a bug - the number of required digits is static as I understand it. For example, a TOTP device/app will always return the same number of digits meaning there's no difference between `int('0072')` and `int(72)`.

**Comment by lmignon** [comment]
@moggers87 you're probably right but user complains that when they receive a generated token starting with '0', the '0' is removed when the form is submitted and the validation fails for the given token.

**Comment by Bouke** [comment]
I think that with this change, mobile devices won't show the on-screen number keyboard.

**Comment by moggers87** [comment]
@lmignon ah, sorry I misunderstood what the issue was.

I've not tested this claim, but according to [this stackoverflow answer](https://stackoverflow.com/a/9318515) it's possible to convince mobile browsers to only display the number pad on a text field using the `pattern` attribute. Does the `RegexField` populate that attribute or is it just a backend check?

**Comment by lmignon** [comment]
@moggers87 
>  Does the RegexField populate that attribute or is it just a backend check?

Yes It's just a backend check.

**Comment by Bouke** [comment]
The referenced answer from SO works as advertised on my iPhone. Not sure about Android, can anyone verify this?

I've updated the code according to this:
```
    otp_token = forms.RegexField(label=_("Token"),
                                 regex=r'^[0-9]*$',
                                 min_length=totp_digits(),
                                 max_length=totp_digits())
    otp_token.widget.attrs.update({
        'autofocus': 'autofocus',
        'pattern': '[0-9]*', # hint to show numeric keyboard for on-screen keyboards
    })
```

img_623599ddc065-1

**Comment by claudep** [comment]
@lmignon, do you think you could rebase your patch and add a test?

**Comment by claudep** [comment]
Patch rebased including tests in #479.

**Pull request closed without merging**
