### PR TITLE
make PhoneBaseMethod.get_devices retrieve all phone devices of the user

### LINKED ISSUE #659: PhoneMethodBase.get_devices only gets devices that are marked as backup
`MethodBase.get_devices` semantics indicate that all user devices that are handled by the method should be retrieved.

## Expected Behavior
It should return all instances of `PhoneDevice` that belong to the user.

## Current Behavior
Since it depends on `two_factor.plugins.phonenumber.utils.backup_phones` only instances named `'backup'` are considered.

### PR DESCRIPTION
**Pull request by jpaniagualaconich**
Fixes #659 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by claudep** [comment]
Now you know what my next comment will be :smile:, test, test, test...

**Comment by jpaniagualaconich** [comment]
@claudep added `two_factor/plugins/phonenumber/tests/test_method.py`

**Review by claudep — APPROVED** [review]
:+1:

**Comment by claudep** [comment]
Minus, the pre-commit failures, but I'm sure they'll get fixed soon!

**Comment by jpaniagualaconich** [comment]
@claudep they are fixed now

**Pull request merged**
