### PR TITLE
Add CONTRIBUTING.rst file

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
This also includes the changes from #445, I'll rebase when the latter is merged.

**Review by Bouke — CHANGES_REQUESTED** [review]
The project uses rst throughout (except for changelog.md), so it would make sense to use the rst version here as well right?

**Comment by claudep** [comment]
No problem, I can convert this new file in rst syntax, probably tomorrow.

**Comment by Bouke** [comment]
There’s also a rst template provided: https://jazzband.co/about/guidelines#contributing-guidelines

**Review by Bouke — APPROVED** [review]

**Pull request merged**
