### PR TITLE
Prepare 1.16.0 release

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@sergei-maertens Do you think we should rather switch to `1.16.0`?

**Comment by sergei-maertens** [comment]
I think 1.16.0 is more appropriate - the webauthn minimal version bump is a rather big change. I think it's also good to mention that users can probably uninstall pydantic if no other dependencies or their own project uses it.

With tooling like `pip-tools` this is managed automatically, but there are plently of people still just freezing their env into a requirements file and they may not need pydantic anymore.

**Comment by claudep** [comment]
> but there are plently of people still just freezing their env into a requirements file

/me whistles innocently...

**Review by sergei-maertens — APPROVED** [review]

**Comment by claudep** [comment]
Thanks a lot @sergei-maertens for your help today!

**Comment by sergei-maertens** [comment]
You're welcome! Feel free to ping me if you're in need of reviewa again

**Pull request merged**
