### PR TITLE
Allow django-phonenumber-field 4.x

### PR DESCRIPTION
**Pull request by Natureshadow**
According to changelog, the version bump was due to a change in handling of invalid phone numbers, that should not break anything existing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by moggers87** [comment]
What's the change exactly? That's a new major version, so clearly upstream think it's a big deal.

**Comment by claudep** [comment]
Changelog for 4.0:
`The big version bump is due to the change in how invalid phone numbers are handled. Starting with 2.4.0 we added very aggressive validation, which raised ValueError for invalid numbers. This caused problems in unexpected places (like when filtering a queryset). Starting with 4.0.0 we acknowledge that we can not completely prevent invalid numbers from entering the system. Changes directly to the database, validation changes in the upstream phonenumbers library, changes in the django settings may all lead to invalid numbers in the database. Now it is possible to save an invalid number to the database and __str__ and __repr__ clearly indicate invalid numbers.`

**Comment by Natureshadow** [comment]
@moggers87 Only if downstream relies on exceptions for normal control flow. If you catch ValueError to validate phone numbers instead of using a validator, this is bad news. But it's your own fault then ;).

In all other cases, it just reacts less indignant to outside changes to the database.

**Comment by moggers87** [comment]
OK, but is that the case for django-two-factor-auth? You say it "should not" break anything, but have you actually tested this?

**Comment by Natureshadow** [comment]
I assume the current test suite does already verify that invalid phone numbers are caught correctly. If not, it is out of the scope of this change.

**Comment by Bouke** [comment]
Any breaking changes resulting from this change are of course within the scope of this change. So that needs to be verified; preferably by the one proposing the change.

**Comment by claudep** [comment]
Superseded by #443

**Pull request closed without merging**
