### PR TITLE
Add jazzband-compatible release GitHub action

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@jezdez, could you please check if this is correct? Is anything else needed to be able to publish through Jazzband? Happy new year!!

**Review by Bouke — APPROVED** [review]

**Review by jezdez — APPROVED** [review]
This is correct!

**Comment by jezdez** [comment]
(I've also added the required secret to the repo)

**Comment by claudep** [comment]
Thanks for checking!

**Pull request merged**
