### PR TITLE
webauthn e2e: increased timeout to fix flakiness

### LINKED ISSUE #548: test_webauthn_attestation_and_assertion flaky?
It looks like `two_factor.plugins.webauthn.tests.test_e2e.E2ETests.test_webauthn_attestation_and_assertion` is randomly failing with a Timeout error. @jpaniagualaconich, do you think we should augment the timeout?

### PR DESCRIPTION
**Pull request by jpaniagualaconich**
## Motivation and Context

Fixes #548

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by claudep** [comment]
Can you please rebase on master?

**Comment by jpaniagualaconich** [comment]
sure thing.

**Comment by claudep** [comment]
:-(

**Comment by jpaniagualaconich** [comment]
At least it's clear things are not gonna get better with moar seconds. I'll look for a different approach.

**Comment by claudep** [comment]
It looks like all recent test runs were successful. Let's hope it's for good!

**Pull request closed without merging**
