### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by bmihelac**
fix Transifex link in README.rst

## Description
simple doc fix

## Motivation and Context
Current link redirects to https://explore.transifex.com/ instead of project page.

## How Has This Been Tested?
-

## Screenshots (if appropriate):
-

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by claudep — CHANGES_REQUESTED** [review]
This obsolete address is also in other files, could you please fix them also in the same commit?

**Comment by bmihelac** [comment]
@claudep thanks and done

**Comment by claudep** [comment]
Just update the commit message and it will be good to go!

**Review by claudep — APPROVED** [review]

**Comment by claudep** [comment]
@bmihelac Thanks! Please next time create branches on a fork instead of directly in the package repo.

**Comment by bmihelac** [comment]
@claudep sure, thanks and sorry for that - I did not noticed I am not creating a branch on my fork until I needed to rebase it.

**Pull request merged**
