### PR TITLE
Modularise parts of the `LoginView`

### PR DESCRIPTION
**Pull request by mpauly**
## Description
I modularized parts of the `LoginView`, as far as I can tell without modifying existing behavior, but providing more hooks to custromize the `LoginView` via inheritance.

Notice how I split the constants defining the steps into `AUTH_STEP` and `FIRST_STEP`. I assume the clearing of the state in `post()` is meant to happen at the first step of the wizard, which does not necessarily have to be the `'auth'` step.

## Motivation and Context
We use a custom version of the `LoginView` that adds an additional step in the login flow before the actual `'auth'` step. At the moment this requires duplicating large amounts of code. By merging this change it would become a lot easier to accommodate such customization without large changes.

## How Has This Been Tested?
We are currently integrating my fork and it allows large parts of the customization we require. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by claudep** [comment]
Could you please make a separate PR with your first commit?

**Comment by claudep** [comment]
I extracted the first commit and pushed to #604.

**Comment by claudep** [comment]
@mpauly, your first commit is now in master, thanks a lot! Would you like to rebase this patch (and merge commits)?

**Comment by mpauly** [comment]
I just rebased against the current `master` and squashed the commits.

**Review by claudep — APPROVED** [review]
Thanks!

**Pull request merged**
