### PR TITLE
Fixes #587 - Avoid unneeded migration for PhoneDevice

### LINKED ISSUE #587: On a clean install, migrations are not in sync with code
## Expected Behavior
I would expect that when creating a new project, installing django-two-factor-auth, and running migrate, that no further migrations would need to be made for the two factor app.

## Current Behavior
When installing django-two-factor-auth and running makemigrations, it is generating a migration for the two_factor app:

```
(venv) % python manage.py migrate      
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, my_app, otp_email, otp_static, otp_totp, sessions, two_factor
Running migrations:
  Applying otp_email.0001_initial... OK
  Applying otp_email.0002_sidechanneldevice_email... OK
  Applying otp_email.0003_emaildevice_email... OK
  Applying otp_email.0004_throttling... OK
  Applying otp_static.0001_initial... OK
  Applying otp_static.0002_throttling... OK
  Applying otp_totp.0001_initial... OK
  Applying otp_totp.0002_auto_20190420_0723... OK
  Applying two_factor.0001_initial... OK
  Applying two_factor.0002_auto_20150110_0810... OK
  Applying two_factor.0003_auto_20150817_1733... OK
  Applying two_factor.0004_auto_20160205_1827... OK
  Applying two_factor.0005_auto_20160224_0450... OK
  Applying two_factor.0006_phonedevice_key_default... OK
  Applying two_factor.0007_auto_20201201_1019... OK
  Applying two_factor.0008_delete_phonedevice... OK
(venv) % python manage.py makemigrations
Migrations for 'two_factor':
  venv/lib/python3.11/site-packages/two_factor/migrations/0009_initial.py
    - Create model PhoneDevice
```

## Possible Solution
If the issue is that a migration is missing, generate and commit it. If the problem is that a model is in the wrong app, perhaps remove it from that app. Note: this issue was introduced in version 1.15.0; if I install 1.14.0 there are no migration issues.

## Steps to Reproduce (for bugs)
1. Follow the installation instructions for django-two-factor auth
2. Run: ``` python manage.py makemigrations```

## Context
This issue can be avoided by only ever generating migrations for my own apps, but that is a bit tedious.

## Your Environment
* Browser and version: N/A
* Python version: 3.11.0
* Django version: 4.1.5
* django-otp version: 1.1.4
* django-two-factor-auth version: 1.15.0
* Link to your project: https://github.com/jessamynsmith/django_4_example

### PR DESCRIPTION
**Pull request by claudep**
Also refs #469.

### CODE REVIEW

**Comment by sevdog** [comment]
Also the migration [`0004_auto_20160205_1827`](https://github.com/jazzband/django-two-factor-auth/blob/master/two_factor/migrations/0004_auto_20160205_1827.py) does not work if phonenumbers is not installed: 


```
  File "/opt/venv/lib/python3.9/site-packages/two_factor/migrations/0004_auto_20160205_1827.py", line 3, in <module>
    import phonenumber_field.modelfields
  File "/opt/venv/lib/python3.9/site-packages/phonenumber_field/modelfields.py", line 7, in <module>
    from phonenumber_field import formfields
  File "/opt/venv/lib/python3.9/site-packages/phonenumber_field/formfields.py", line 1, in <module>
    import phonenumbers
```

**Comment by claudep** [comment]
@sevdog, good catch. I tried avoiding this by squashing migrations in #597.

**Comment by claudep** [comment]
Tweaking the migrations is probably unneeded after 2ff98b514d. Patch needs rework.

**Comment by mgax** [comment]
> Tweaking the migrations is probably unneeded after [2ff98b5](https://github.com/jazzband/django-two-factor-auth/commit/2ff98b514d42db97d7c9fdabe2face86fc6f8188). Patch needs rework.

On master, I've tried to simply comment out the _phonenumber_ URLs from `two_factor/urls.py` and the migration is still being generated; stubbing out `key_validator` in migrations did the trick.

What is needed for the patch to be merged? I'd like to help.

**Comment by claudep** [comment]
I guess that another less-invasive approach could be to conditionally include phonenumber urls in main urls by testing if the app is installed. I would be interested to collect opinions about this (the challenge being: avoid importing phonenumber stuff in main urls).

**Comment by dekkers** [comment]
There is also the option of keeping all the names of the urls of the phonenumber plugin in the two_factor namespace to avoid breaking backwards compatability. I am not really sure what the best way is to propose changes to an existing PR, but I did that in this commit and that seems to work:

https://github.com/dekkers/django-two-factor-auth/commit/70a45b8dc021125c71760390d1434723d92f1875

**Comment by claudep** [comment]
Nice! I merged your commit in my PR.

**Pull request merged**
