### PR TITLE
Increase template overridability

### PR DESCRIPTION
**Pull request by PetrDlouhy**
I have added few code blocks to `login.html` template. This reduces the need for code duplication in overriding templates.

This PR contains commit from #546 to eliminate need to code changes after that PR gets merged. I expect that #546 well be merged first.

## Description
Code blocks allows to override only part of given template.

## Motivation and Context
Reduce code duplication.

## How Has This Been Tested?
Tox, manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@claudep Can you please review this? I have added the form extra params in separate PR as you asked as well as blocks to increase the template overridability.

**Comment by claudep** [comment]
It seems to me that there are a lots of blocks now, isn't this a bit too much? I guess that if you really need all those blocks, you'd rather write your own template. We could add blocks that match an obvious and frequent use case. That's just an overall feeling, and I'd appreciate other opinions on the patch.

**Comment by PetrDlouhy** [comment]
@claudep Thank you for your comment. I guess you are right, I can achieve almost the same code reusage with only one additional block in the original template.
The main form content block enables me to reuse quite some block of code, and I expect it could be helpful also for others.

Would this be sufficient to get merged?

**Review by claudep — APPROVED** [review]
Looks good and simple!

**Pull request merged**
