### PR TITLE
Changing hidden input submit to facilitate hidden property not css

### PR DESCRIPTION
**Pull request by yopiti**
Setting field to hidden, to avoid conflict with pages that are not using Bootstrap as CSS framework

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by yopiti** [comment]
Can you please merge this?

**Comment by moggers87** [comment]
The template has the comment `{# hidden submit button to enable [enter] key #}` above that input - does that still work with a hidden input? I can't imagine it does.

**Review by moggers87 — DISMISSED** [review]
:+1:

**Review by moggers87 — CHANGES_REQUESTED** [review]
There are other places in our templates where this same issue occurs, see https://github.com/jazzband/django-two-factor-auth/search?q=d-none&type=code

**Review by claudep — APPROVED** [review]

**Pull request merged**
