### PR TITLE
Delete two_factor/migrations/0001_squashed_0008_delete_phonedevice.py

### PR DESCRIPTION
**Pull request by hyperkai**
This file causes the error below so I deleted it:

> django.db.utils.OperationalError: no such table: two_factor_phonedevice

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hyperkai** [comment]
I deleted `two_factor/migrations/0001_squashed_0008_delete_phonedevice.py` because the file causes the error below:

django.db.utils.OperationalError: no such table: two_factor_phonedevice

**Comment by hyperkai** [comment]
I deleted two_factor/migrations/0001_squashed_0008_delete_phonedevice.py because the file causes the error below:

django.db.utils.OperationalError: no such table: two_factor_phonedevice

**Comment by pacharanero** [comment]
Not sure if this is directly related but we do also seem to have an issue with unapplied migrations having recently implemented `two_factor` in our app. We have a step in our Docker Compose file which runs `python manage.py migrate` but for some reason we don't understand this one migration is not being applied.

We get a warning in the log console "You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): two_factor." and when entering the relevant Docker container and running `python manage.py migrate` again, it then applies the migration: `Applying two_factor.0001_squashed_0008_delete_phonedevice... OK` but we don't see why this should be necessary when all our other migrations get applied automatically during the provisioning of the Docker Compose setup.

**Comment by mlec1** [comment]
@hyperkai I would suggest opening an issue instead. 

Which version of the package are you using ? The table you mention is not in the file you want to delete. It is in the `phonenumber` plugin

**Comment by moggers87** [comment]
Closing this as I think this is a duplicate of #647

**Pull request closed without merging**
